// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj9MJ4x_iqrzbGOEDcgwWt-WP40Du-Ji4',
    appId: '1:914982985085:web:ba57157755e41445e9c014',
    messagingSenderId: '914982985085',
    projectId: 'dreamsacco-84659',
    authDomain: 'dreamsacco-84659.firebaseapp.com',
    storageBucket: 'dreamsacco-84659.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJZke0_EnRtvg4lAQ6GyOjlVIETZIuBl8',
    appId: '1:914982985085:android:817bbfc973e2237fe9c014',
    messagingSenderId: '914982985085',
    projectId: 'dreamsacco-84659',
    storageBucket: 'dreamsacco-84659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUoHEuTI5sKlr9_uewgF_p9Ln5u6aouaM',
    appId: '1:914982985085:ios:c0ceb564a532192fe9c014',
    messagingSenderId: '914982985085',
    projectId: 'dreamsacco-84659',
    storageBucket: 'dreamsacco-84659.firebasestorage.app',
    iosBundleId: 'com.dreamsacco.dreamsacco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUoHEuTI5sKlr9_uewgF_p9Ln5u6aouaM',
    appId: '1:914982985085:ios:c0ceb564a532192fe9c014',
    messagingSenderId: '914982985085',
    projectId: 'dreamsacco-84659',
    storageBucket: 'dreamsacco-84659.firebasestorage.app',
    iosBundleId: 'com.dreamsacco.dreamsacco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj9MJ4x_iqrzbGOEDcgwWt-WP40Du-Ji4',
    appId: '1:914982985085:web:74dd98860cf4b015e9c014',
    messagingSenderId: '914982985085',
    projectId: 'dreamsacco-84659',
    authDomain: 'dreamsacco-84659.firebaseapp.com',
    storageBucket: 'dreamsacco-84659.firebasestorage.app',
  );
}
